/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RoomService;

import RoomService.dashboardServer.DashboardServer;

public class App {
	
	final static int PORT = 80;

    public static void main(String[] args) {
    	new DashboardServer(PORT).start();
    }
}
