/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RoomService;

import RoomService.dashboardServer.DashboardServer;

public class App {
	
	final static int port = 80;

    public static void main(String[] args) {
    	DashboardServer server = new DashboardServer(port);
    	server.runServer();
    }
}
